export const Democurse = [
    {
      id: 1,
      Course_name:'ภาษาอังกฤษเพื่อการสื่อสารในสังคม',
      Class_houurs: 4,
      Cost: "free",
      Description:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน เช่น การเข้าพักโรงแรม การซื้อของ อาการและเครื่องดื่ม การถามทาง",
      Description2:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน ",
      Instrutor:"พศิกา ธารณธรรม",
      Instrutor_Email:"pasika@gmail.com",
      Instrutor_Phone:"034109300",
      Lessons:4,
      Limit_class:50,
      Specified_criteria:"ผู้เรียนมีคะแนนรวมทั้งหมดไม่ต่ำกว่า 70% ถือว่าผ่านเกณฑ์เพื่อรับประกาศนียบัตรในระบบได้",
      Subject:"ภาษาอังกฤษเพื่อการสื่อสารในสังคม (English for Social Communication)",
      TypeClass:"ภาษาและการสื่อสาร"
    },
    {
        id: 2,
        Course_name:'การพัฒนาแอปพลิเคชันด้วยภาษา swift',
        Class_houurs: 4,
        Cost: "free",
        Description:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน เช่น การเข้าพักโรงแรม การซื้อของ อาการและเครื่องดื่ม การถามทาง",
        Description2:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน ",
        Instrutor:"พศิกา ธารณธรรม",
        Instrutor_Email:"pasika@gmail.com",
        Instrutor_Phone:"034109300",
        Lessons:4,
        Limit_class:50,
        Specified_criteria:"ผู้เรียนมีคะแนนรวมทั้งหมดไม่ต่ำกว่า 70% ถือว่าผ่านเกณฑ์เพื่อรับประกาศนียบัตรในระบบได้",
        Subject:"ภาษาอังกฤษเพื่อการสื่อสารในสังคม (English for Social Communication)",
        TypeClass:"ภาษาและการสื่อสาร"
    },
    {
        id: 3,
        Course_name:'ภาษาอังกฤษเพื่อการประชุม',
        Class_houurs: 4,
        Cost: "free",
        Description:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน เช่น การเข้าพักโรงแรม การซื้อของ อาการและเครื่องดื่ม การถามทาง",
        Description2:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน ",
        Instrutor:"พศิกา ธารณธรรม",
        Instrutor_Email:"pasika@gmail.com",
        Instrutor_Phone:"034109300",
        Lessons:4,
        Limit_class:50,
        Specified_criteria:"ผู้เรียนมีคะแนนรวมทั้งหมดไม่ต่ำกว่า 70% ถือว่าผ่านเกณฑ์เพื่อรับประกาศนียบัตรในระบบได้",
        Subject:"ภาษาอังกฤษเพื่อการสื่อสารในสังคม (English for Social Communication)",
        TypeClass:"ภาษาและการสื่อสาร"
    },
    {
        id: 4,
        Course_name:'ภาษาอังกฤษเพื่อการนำเสนอ',
        Class_houurs: 4,
        Cost: "free",
        Description:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน เช่น การเข้าพักโรงแรม การซื้อของ อาการและเครื่องดื่ม การถามทาง",
        Description2:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน ",
        Instrutor:"พศิกา ธารณธรรม",
        Instrutor_Email:"pasika@gmail.com",
        Instrutor_Phone:"034109300",
        Lessons:4,
        Limit_class:50,
        Specified_criteria:"ผู้เรียนมีคะแนนรวมทั้งหมดไม่ต่ำกว่า 70% ถือว่าผ่านเกณฑ์เพื่อรับประกาศนียบัตรในระบบได้",
        Subject:"ภาษาอังกฤษเพื่อการสื่อสารในสังคม (English for Social Communication)",
        TypeClass:"ภาษาและการสื่อสาร"
    },
    {
        id: 5,
        Course_name:'เรียนรู้การสร้างธุรกิจด้วย Leancanvan',
        Class_houurs: 4,
        Cost: "free",
        Description:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน เช่น การเข้าพักโรงแรม การซื้อของ อาการและเครื่องดื่ม การถามทาง",
        Description2:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน ",
        Instrutor:"พศิกา ธารณธรรม",
        Instrutor_Email:"pasika@gmail.com",
        Instrutor_Phone:"034109300",
        Lessons:4,
        Limit_class:50,
        Specified_criteria:"ผู้เรียนมีคะแนนรวมทั้งหมดไม่ต่ำกว่า 70% ถือว่าผ่านเกณฑ์เพื่อรับประกาศนียบัตรในระบบได้",
        Subject:"ภาษาอังกฤษเพื่อการสื่อสารในสังคม (English for Social Communication)",
        TypeClass:"ภาษาและการสื่อสาร"
    },
    {
        id: 6,
        Course_name:'การออกแบบUX/UI',
        Class_houurs: 4,
        Cost: "free",
        Description:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน เช่น การเข้าพักโรงแรม การซื้อของ อาการและเครื่องดื่ม การถามทาง",
        Description2:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน ",
        Instrutor:"พศิกา ธารณธรรม",
        Instrutor_Email:"pasika@gmail.com",
        Instrutor_Phone:"034109300",
        Lessons:4,
        Limit_class:50,
        Specified_criteria:"ผู้เรียนมีคะแนนรวมทั้งหมดไม่ต่ำกว่า 70% ถือว่าผ่านเกณฑ์เพื่อรับประกาศนียบัตรในระบบได้",
        Subject:"ภาษาอังกฤษเพื่อการสื่อสารในสังคม (English for Social Communication)",
        TypeClass:"ภาษาและการสื่อสาร"
    },
    
  ];

  export const Mycoursedeme = [
    
    {
        id: 2,
        Course_name:'การพัฒนาแอปพลิเคชันด้วยภาษา swift',
        Class_houurs: 4,
        Cost: "free",
        Description:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน เช่น การเข้าพักโรงแรม การซื้อของ อาการและเครื่องดื่ม การถามทาง",
        Description2:"การพัฒนาทักษaะการใช้ภาษาจีนเพื่อการสื่อสารในชีวิตประจำวัน ",
        Instrutor:"พศิกา ธารณธรรม",
        Instrutor_Email:"pasika@gmail.com",
        Instrutor_Phone:"034109300",
        Lessons:4,
        Limit_class:50,
        Specified_criteria:"ผู้เรียนมีคะแนนรวมทั้งหมดไม่ต่ำกว่า 70% ถือว่าผ่านเกณฑ์เพื่อรับประกาศนียบัตรในระบบได้",
        Subject:"ภาษาอังกฤษเพื่อการสื่อสารในสังคม (English for Social Communication)",
        TypeClass:"ภาษาและการสื่อสาร"
    },

];